- CHANGELOG.md
- Gemfile.lock
- app/controllers/rpi_auth/auth_controller.rb
- lib/rpi_auth/configuration.rb
- lib/rpi_auth/version.rb
- spec/dummy/config/initializers/rpi_auth.rb
It should generally be allowed to default to the `omniauth.origin` value (which ensures that the user is returned to the page at which they made the request): https://github.com/RaspberryPiFoundation/rpi-auth/blob/37ac1d441498a3e56c6431c880e4d054cd108695/app/controllers/rpi_auth/auth_controller.rb#L14-L20
> Don't set success_redirect = '/' by default

- CHANGELOG.md
- Gemfile.lock
- README.md
- app/controllers/rpi_auth/auth_controller.rb
- lib/rpi_auth/models/authenticatable.rb
- spec/dummy/app/models/user.rb
- spec/requests/auth_request_spec.rb
- spec/rpi_auth/models/authenticatable_spec.rb
- spec/rpi_auth_spec.rb
Allow `Authenticatable` to be extendable, giving access to custom methods and attributes without having to change the base module.
> fix(Authenticatable-model): access from_omniauth via User model

- CHANGELOG.md
- Gemfile.lock
- README.md
- config/routes.rb
- gemfiles/rails_6.1.gemfile.lock
- lib/rpi_auth/configuration.rb
- lib/rpi_auth/engine.rb
- lib/rpi_auth_bypass.rb
- rpi_auth.gemspec
- spec/dummy/app/controllers/home_controller.rb
- spec/dummy/app/views/home/show.html.erb
- spec/dummy/app/views/layouts/application.html.erb
- spec/dummy/config/environments/development.rb
- spec/dummy/config/initializers/rpi_auth.rb
- spec/dummy/config/routes.rb
- spec/dummy/spec/requests/auth_request_spec.rb
- spec/dummy/spec/views/home_show_spec.rb
- spec/rpi_auth/configuration_spec.rb
- spec/rpi_auth_bypass_spec.rb
- spec/spec_helper.rb
- spec/support/omniauth.rb
- spec/support/request_helpers.rb
* Removed omniauth-rpi
* Added omniauth_openid_connect 
* Added helper methods to RpiAuth::Configuration class to help set up the openid_connect client
* Adjusted how the tests were run to make sure OmniAuth test mode was toggled correctly
* Moved RpiAuthBypass + tests from omniauth-rpi to this gem
* Fixed up dummy app to work for local development.
I don't *think* any reconfiguration is necessary for clients to move from omniauth-rpi to omniauth_openid_connect thanks to the smoothing out performed in this gem.
The RpiAuthBypass is a bit.. rustic.   It has just been transplanted from omniauth-rpi, but I suspect the implementation could be refined to make it more useful, and less likely to breakage as Hydra / omniauth_openid_connect develop.  Ideally we'd have a check to make sure the auth …
> Use omniauth openid connect

- CHANGELOG.md
- Gemfile.lock
- gemfiles/rails_6.1.gemfile.lock
- lib/rpi_auth/version.rb
This is a major release, as we've replaced the underlying OmniAuth library, which might cause some implementation/usage changes.
- Replaced usage of [omniauth-rpi](https://github.com/RaspberryPiFoundation/omniauth-rpi/) strategy with [omniauth_openid_connect](https://github.com/omniauth/omniauth_openid_connect/) (#51)
> Release v3.0.0

- CHANGELOG.md
- config/routes.rb
- lib/rpi_auth/engine.rb
- spec/dummy/config/initializers/rpi_auth.rb
When multiple redirect URIs are set in Hydra, it needs a redirect_uri param specifying.   I had assumed that the `callback_path` would be enough, but it turns out I was wrong.
This expeclicitly sets the redirect_uri parameter when initiating the login flow.
> Set redirect uri

- CHANGELOG.md
- README.md
- lib/rpi_auth/configuration.rb
- spec/dummy/config/initializers/rpi_auth.rb
- spec/rpi_auth/configuration_spec.rb
I was confusing myself when running Hydra v1.11 (rather than v1.9) and decided that the issuer should be based on the `token_endpoint` rather than the `authorization_endpoint`. 
In 1.11 it is possible to specify the `SELF_PUBLIC_URL` value to split between URLs that should be queried by the browser, and those queried by the hydra client (ie.. the rails app).  This helps with discovery, but ends up with the `SELF_ISSUER_URL` being `docker.host.internal` such that the other endpoints are correctly set.
This PR simplifies things back to match with v1.9 😅 meaning that we don't have to see the issuer by hand.
> Update issuer value to default to the authorization_endpoint

- CHANGELOG.md
- Gemfile.lock
- gemfiles/rails_6.1.gemfile.lock
- lib/rpi_auth/version.rb
- Altered default value of the `issuer` to track the `authorization_endpoint` rather than the `token_endpoint` (#54)
- Ensure `redirect_uri` is set in the OpenID Connect configuration (#53)
> Release v3.1.0

- CHANGELOG.md
- README.md
- app/controllers/rpi_auth/auth_controller.rb
- spec/dummy/spec/requests/auth_request_spec.rb
Closes #46 
* A returnTo parameter can be added to the logout path to redirect users to a different place having logged out.
* Altered how we handle returnTo parameters in general, as Rails 6 doesn't check for open redirects
> Allow customising of the logout returnTo URL

- CHANGELOG.md
- README.md
- app/controllers/rpi_auth/auth_controller.rb
- spec/dummy/config/initializers/rpi_auth.rb
- spec/dummy/spec/requests/auth_request_spec.rb
This allows a `proc` to be used as a `success_redirect` value.  This is particularly useful if you need to generated URLs based on the one of the parameters returned or applied during the callback function.
It is of particular interest in CoderDojo frontend, which needs to send a user to Zen to log in, but also redirect the user back to the correct page in CoderDojo frontend afterwards.  So the Zen URL will need to have a dynamic returnTo parameter based on the original returnTo param supplied to omniauth.
* The proc is executed using `instance_exec` to make sure it is run in the context of the controller, rather than the context of the configuration block where it is first defined.
* I've tried to document this as best as possible!
> Add dynamic `success_redirect` URLs to be generated

- CHANGELOG.md
- lib/rpi_auth/models/authenticatable.rb
- spec/rpi_auth/models/authenticatable_spec.rb
Add `#country` as an attribute in `Authenticable`.
This is to support work in experience-ai, see https://github.com/RaspberryPiFoundation/experience-ai/issues/205
> Add country to Authenticable

- config/routes.rb
- spec/dummy/spec/views/home_show_spec.rb
No longer needed, since we now assume all log in / sign ups to Profile should use the v1 flow (since migrating fully to Hydra v1).
Depends on: https://github.com/RaspberryPiFoundation/profile/pull/1512
> Removes v1_signup param

- .github/workflows/test.yml
Update the versions of some github actions to stop using the deprecated versions. HIdden files are now excluded by default so allowed them in the upload to get the `.last_run.json` needed included.
> new versions for github actions

- Rakefile
Previously it wasn't even possible to list the rake tasks, because this `rails/tasks/statistics.rake` file does not exist.
It was added in [a very large initial commit][1] which doesn't mention it in the commit note, so I have no idea what its origins are.
[1]: https://github.com/RaspberryPiFoundation/rpi-auth/commit/79600c924364ecf9edcd05800739b2b193708ac1
> Avoid LoadError when using rake

- lib/rpi_auth/controllers/current_user.rb
- spec/dummy/app/controllers/home_controller.rb
- spec/dummy/config/routes.rb
- spec/dummy/spec/requests/auth_request_spec.rb
This is a bit of an edge case, but if the user is logged in and then the session is reset (or at least its `current_user` value is reset) and `RpiAuth::Controllers::CurrentUser#current_user` is called within the *same* request, then previously it would have returned the user "cached" in the `@current_user`. Now it will return `nil` which seems less surprising.
This was highlighted by [this example][1] in code-club-frontend. In that case the example passes, because that app has [its own implementation of `#current_user`][2]. However, when I added a similar example in experience-cs where we're using `RpiAuth::Controllers::CurrentUser#current_user`, the example failed.
I've added a rather contrived example by adding a new `HomeController#reset_user` action to the dummy app used in the specs. …
> Don't use cached user if session has been reset

- CHANGELOG.md
- gemfiles/rails_6.1.gemfile.lock
- gemfiles/rails_7.0.gemfile.lock
- gemfiles/rails_7.1.gemfile.lock
- gemfiles/rails_7.2.gemfile.lock
- lib/rpi_auth/version.rb
- [Add `CHANGELOG` entry for #79](https://github.com/RaspberryPiFoundation/rpi-auth/commit/00004283d0e9dc8a75cc813ef5ef7d3ea109b8f5)
- [Update `CHANGELOG` & `RpiAuth::VERSION` in preparation to release v4.0.0](https://github.com/RaspberryPiFoundation/rpi-auth/commit/7a82a3002d4e27dfa385be5994fa481ad982f555)
> Release v4.0.0

- CHANGELOG.md
- lib/rpi_auth/spec_helpers.rb
Previously, if `User#expires_at` was defined, but it was set to `nil`, the `expires_in` calculation was returning a large negative integer. This was because `nil.to_i` is 0 and thus `user.expires_at.to_i - Time.zone.now.to_i` was a value like `-1744820986` (for 2025-04-16 17:30) which meant the credentials were effectively immediately expired some time ago.
This isn't a problem in e.g. `code-club-frontend`, because [the user factory sets `User#expires_at` to a time a random number of seconds in the future, i.e. `rand(60..300).seconds.from_now][1].
We've had to do [something similar in `experience-cs`][2], but I think a better solution is to default to using the 3600 fallback value if `User#expires_at` is `nil` just like we do if `User#expires_at` is not defined.
[1]: …
> Fix use of `User#expires_at` in `SpecHelpers#stub_auth_for`

- .github/workflows/test.yml
- lib/rpi_auth/spec_helpers.rb
- spec/dummy/spec/requests/auth_request_spec.rb
This fixes some existing rubocop violations via the auto-correct mechanism and then adds rubocop to the CI build as an extra step in the "test" job, but only executing for Ruby v3.3 and Rails v7.2 (currently the latest version of each being tested).
> Add rubocop to CI build

- .rubocop_todo.yml
- CHANGELOG.md
- README.md
- gemfiles/rails_6.1.gemfile.lock
- gemfiles/rails_7.0.gemfile.lock
- gemfiles/rails_7.1.gemfile.lock
- gemfiles/rails_7.2.gemfile.lock
- lib/rpi_auth.rb
- lib/rpi_auth/controllers/auto_refreshing_token.rb
- lib/rpi_auth/controllers/current_user.rb
- lib/rpi_auth/models/authenticatable.rb
- lib/rpi_auth/models/with_tokens.rb
- lib/rpi_auth/oauth_client.rb
- rpi_auth.gemspec
- spec/dummy/app/controllers/application_controller.rb
- spec/dummy/app/models/user.rb
- spec/dummy/spec/requests/refresh_credentials_spec.rb
- spec/rpi_auth/models/with_tokens_spec.rb
- spec/rpi_auth/oauth_client_spec.rb
- spec/spec_helper.rb
- spec/support/webmock.rb
The following new functionality has been **extracted** from `code-club-frontend` and `experience-cs` to reduce duplication and hopefully make useful functionality available to other Rails apps using this gem.
[This pull request](https://github.com/RaspberryPiFoundation/experience-cs/pull/295) where it was recently added to `experience-cs` and [this follow-up pull request](https://github.com/RaspberryPiFoundation/experience-cs/pull/315) are good references.
* ✅  I've used the new `rpi-auth` code in the context of `experience-cs` in [this pull request](https://github.com/RaspberryPiFoundation/experience-cs/pull/317) and it seems to be OK.
* ✅  I've used the new `rpi-auth` code in the context of `code-club-frontend` in [this pull request](https://github.com/RaspberryPiFoundation/code-club-fro …
> Add access token-related functionality including auto-refresh

- CHANGELOG.md
- gemfiles/rails_6.1.gemfile.lock
- gemfiles/rails_7.0.gemfile.lock
- gemfiles/rails_7.1.gemfile.lock
- gemfiles/rails_7.2.gemfile.lock
- lib/rpi_auth/version.rb
- Minor version bump (v4.0.0 -> v4.1.0), because release only includes additions and a bug fix.
- Changelog updated (including the link references at the bottom).
> Prepare to release v4.1.0

- CHANGELOG.md
- gemfiles/rails_6.1.gemfile.lock
- gemfiles/rails_7.0.gemfile.lock
- gemfiles/rails_7.1.gemfile.lock
- gemfiles/rails_7.2.gemfile.lock
- lib/rpi_auth/controllers/auto_refreshing_token.rb
- lib/rpi_auth/oauth_client.rb
- lib/rpi_auth/version.rb
- spec/dummy/spec/requests/refresh_credentials_spec.rb
- spec/rpi_auth/oauth_client_spec.rb
The changes in #83 (which were released in v4.1.0) moved the `OauthClient` class (which uses the `oauth2` gem) from the Rails applications into the `rpi_auth` gem. At that point the `oauth2` gem was made a direct dependency of `rpi_auth` and the direct dependency on `oauth2` was removed from the Rails applications.
I _think_ this meant that the `oauth2` gem was no longer being required automatically. And, although individual files in the `oauth2` gem were being required from individual files in `rpi_auth`, this meant that not all of the files in `oauth2` were being required. In particular, the `lib/oauth2.rb` file which defines the top-level `OAuth2` module and the `OAuth2.config` method was no longer being required. This led to exceptions like [this one][1] in `experience-cs` when …
> Fix requiring of oauth2
